trigger:
  - master
  - develop
  - release/*
  - feature/*

variables:
  assimpVersion: 5.0.1
  assimpNetVersion: 5.0.0-beta1
  package_folder: com.arsenstudio.assimp
  publish_feed: stable

  windows_enabled: true
  macosx_enabled: true
  linux_enabled: true
  ios_enabled: true
  android_enabled: true

stages:

########################################################################################################################
## Build
########################################################################################################################

  - stage: build
    displayName: Build
    jobs:
      ## AssimpNet
      - job: build_assimpnet
        displayName: AssimpNet
        pool:
          vmImage: 'windows-2019'
        variables:
          solution: 'AssimpNet.sln'
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'
        steps:
          - checkout: none

          - bash: curl -L https://github.com/intelligide/assimpnet-unity/archive/$(assimpNetVersion).zip -o assimpnet.zip
            displayName: Download AssimpNet sources

          - task: ExtractFiles@1
            displayName: Extract AssimpNet sources
            inputs:
              archiveFilePatterns: "assimpnet.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - task: NuGetToolInstaller@1
            displayName: Nuget installation

          - task: NuGetCommand@2
            displayName: Restore solution
            inputs:
              command: restore
              restoreSolution: assimpnet-unity-$(assimpNetVersion)/$(solution)

          - task: VSBuild@1
            displayName: Build AssimpNet
            inputs:
              solution: assimpnet-unity-$(assimpNetVersion)/$(solution)
              platform: $(buildPlatform)
              configuration: $(buildConfiguration)

          - publish: $(System.DefaultWorkingDirectory)/assimpnet-unity-$(assimpNetVersion)/AssimpNet/bin/Release/net4/AssimpNet.dll
            artifact: AssimpNet-net4

          - publish: $(System.DefaultWorkingDirectory)/assimpnet-unity-$(assimpNetVersion)/AssimpNet/bin/Release/netstandard1.3/AssimpNet.dll
            artifact: AssimpNet-netstandard1.3

      ## Windows
      - job: build_assimp_win
        displayName: Assimp for Windows
        condition: eq('${{ variables.windows_enabled }}', 'true')
        strategy:
          matrix:
            x86_64:
              cmakeGeneratorArch: x64
              buildArch: x64
            x86:
              cmakeGeneratorArch: Win32
              buildArch: x86
        pool:
          vmImage: 'windows-2019'
        steps:
          - checkout: none

          - bash: curl -L https://github.com/assimp/assimp/archive/v$(assimpVersion).zip -o assimp.zip
            displayName: Download Assimp sources

          - task: ExtractFiles@1
            displayName: Extract Assimp sources
            inputs:
              archiveFilePatterns: "assimp.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - task: CMake@1
            displayName: Configure Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: -G "Visual Studio 16 2019" -A $(cmakeGeneratorArch) -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel
                -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON -DLIBRARY_SUFFIX=""
                -DINJECT_DEBUG_POSTFIX=OFF -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)

          - task: CMake@1
            displayName: Build Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --config MinSizeRel

          - task: CMake@1
            displayName: Install Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --target install --config MinSizeRel

          - publish: $(Build.BinariesDirectory)/bin/assimp.dll
            artifact: Assimp-Win-$(buildArch)

      ## Linux
      - job: build_assimp_linux
        displayName: Assimp for Linux
        condition: eq('${{ variables.linux_enabled }}', 'true')
        strategy:
          matrix:
            x86_64:
              buildArch: x64
        variables:
          CFLAGS: -g0 -s -Wl,-s
          CXXFLAGS: -g0 -s -Wl,-s
          LDFLAGS: -g0 -s -Wl,-s
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - checkout: none

          - bash: sudo apt-get update -yqq && sudo apt install -y ninja-build
            displayName: Install Ninja

          - bash: curl -L https://github.com/assimp/assimp/archive/v$(assimpVersion).zip -o assimp.zip
            displayName: Download Assimp sources

          - task: ExtractFiles@1
            displayName: Extract Assimp sources
            inputs:
              archiveFilePatterns: "assimp.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - task: CMake@1
            displayName: Configure Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: -G Ninja -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel -DASSIMP_BUILD_TESTS=OFF
                -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)

          - task: CMake@1
            displayName: Build Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --config MinSizeRel

          - task: CMake@1
            displayName: Install Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --target install --config MinSizeRel

          - publish: $(Build.BinariesDirectory)/lib/libassimp.so
            artifact: Assimp-Linux-$(buildArch)

      ## Android
      - job: build_assimp_android
        displayName: Assimp for Android
        condition: eq('${{ variables.android_enabled }}', 'true')
        strategy:
          matrix:
            armv7:
              androidABI: armeabi-v7a
            arm64:
              androidABI: arm64-v8a
            x86:
              androidABI: x86
        variables:
          CFLAGS: -g0 -s -Wl,-s
          CXXFLAGS: -g0 -s -Wl,-s
          LDFLAGS: -g0 -s -Wl,-s
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - checkout: none

          - bash: sudo apt-get update -yqq && sudo apt install -y ninja-build
            displayName: Install Ninja

          - bash: curl -L https://github.com/assimp/assimp/archive/v$(assimpVersion).zip -o assimp.zip
            displayName: Download Assimp sources

          - task: ExtractFiles@1
            displayName: Extract Assimp sources
            inputs:
              archiveFilePatterns: "assimp.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - task: CMake@1
            displayName: Configure Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: -G Ninja -S . -B . -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=$(androidABI)
                -DASSIMP_BUILD_TESTS=OFF -DASSIMP_ANDROID_JNIIOSYSTEM=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
                -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
                -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory) -DANDROID_STL=c++_shared

          - task: CMake@1
            displayName: Build Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --config MinSizeRel

          - task: CMake@1
            displayName: Install Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --target install/strip --config MinSizeRel

          - publish: $(Build.BinariesDirectory)/lib/libassimp.so
            artifact: Assimp-Android-$(androidABI)

      ## macOS
      - job: build_assimp_macos
        displayName: Assimp for Mac OS
        condition: eq('${{ variables.macosx_enabled }}', 'true')
        pool:
          vmImage: 'macOS-10.15'
          strategy:
            matrix:
              x86_64: {}
        variables:
          CFLAGS: -g0
          CXXFLAGS: -g0
          LDFLAGS: -g0 -s
        steps:
          - checkout: none

          - bash: curl -L https://github.com/assimp/assimp/archive/v$(assimpVersion).zip -o assimp.zip
            displayName: Download Assimp sources

          - task: ExtractFiles@1
            displayName: Extract Assimp sources
            inputs:
              archiveFilePatterns: "assimp.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - task: CMake@1
            displayName: Configure Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: -G "Unix Makefiles" -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
                -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)

          - task: CMake@1
            displayName: Build Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --config MinSizeRel

          - task: CMake@1
            displayName: Install Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --target install/strip --config MinSizeRel

          - publish: $(Build.BinariesDirectory)/lib/libassimp.dylib
            artifact: Assimp-macOS-x86_64

      ## iOS
      - job: build_assimp_ios
        displayName: Assimp for iOS
        condition: eq('${{ variables.ios_enabled }}', 'true')
        pool:
          vmImage: 'macOS-10.15'
        strategy:
          matrix:
            armv7:
              buildArch: armv7
            arm64:
              buildArch: arm64
            x86_64:
              buildArch: x86_64
        variables:
          CFLAGS: -g0
          CXXFLAGS: -g0
          LDFLAGS: -g0 -s
        steps:
          - checkout: self

          - bash: curl -L https://github.com/assimp/assimp/archive/v$(assimpVersion).zip -o assimp.zip
            displayName: Download Assimp sources

          - task: ExtractFiles@1
            displayName: Extract Assimp sources
            inputs:
              archiveFilePatterns: "assimp.zip"
              destinationFolder:
              cleanDestinationFolder: false

          - bash: cd assimp-$(assimpVersion) && $(Build.SourcesDirectory)/build-scripts/ios/configure_cmake.sh --arch="$(buildArch)"
              -S=. -B=. -I=$(Build.BinariesDirectory) --stdlib=libc++ --std=c++14
            displayName: Configure Assimp

          - task: CMake@1
            displayName: Build Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --config MinSizeRel

          - task: CMake@1
            displayName: Install Assimp
            inputs:
              workingDirectory: assimp-$(assimpVersion)
              cmakeArgs: --build . --target install/strip --config MinSizeRel

          - publish: $(Build.BinariesDirectory)/lib/libassimp.a
            artifact: Assimp-iOS-$(buildArch)

      ## Docs
      - job: build_docs
        displayName: Docs
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: UseRubyVersion@0
            inputs:
              versionSpec: '>= 2.4 <3.0'

          - script: gem install bundler
            displayName: Install bundler
            workingDirectory: $(build.SourcesDirectory)/docs

          - script: bundle install
            displayName: Install deps
            workingDirectory: $(build.SourcesDirectory)/docs

          - script: bundle exec jekyll build -d $(build.binariesDirectory)/_site
            displayName: Build docs with Jekyll
            workingDirectory: $(build.SourcesDirectory)/docs

          - publish: $(build.binariesDirectory)/_site
            artifact: Docs

########################################################################################################################
## Packaging
########################################################################################################################

  - stage: packaging
    displayName: Packaging
    jobs:
      - job: packaging
        displayName: Packaging
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - download: current

          - task: CopyFiles@2
            displayName: Copy docs
            inputs:
              sourceFolder: $(Pipeline.Workspace)/Docs
              targetFolder: $(build.SourcesDirectory)/$(package_folder)/Documentation~

          - script: yes | cp -f $(Pipeline.Workspace)/AssimpNet-netstandard1.3/AssimpNet.dll $(build.SourcesDirectory)/$(package_folder)/AssimpNet.dll
            displayName: Install AssimpNet

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Win-x64/assimp.dll $(build.SourcesDirectory)/$(package_folder)/Plugins/win/x86_64/assimp.dll
            displayName: Install Assimp for Windows x64
            condition: eq('${{ variables.windows_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Win-x86/assimp.dll $(build.SourcesDirectory)/$(package_folder)/Plugins/win/x86/assimp.dll
            displayName: Install Assimp for Windows x86
            condition: eq('${{ variables.windows_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Linux-x64/libassimp.so $(build.SourcesDirectory)/$(package_folder)/Plugins/linux/x86_64/libassimp.so
            displayName: Install Assimp for Linux x86_64
            condition: eq('${{ variables.linux_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-macOS-x86_64/libassimp.dylib $(build.SourcesDirectory)/$(package_folder)/Plugins/osx/x86_64/libassimp.dylib
            displayName: Install Assimp for Mac OS X x86_64
            condition: eq('${{ variables.macosx_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Android-armeabi-v7a/libassimp.so $(build.SourcesDirectory)/$(package_folder)/Plugins/android/armv7/libassimp.so
            displayName: Install Assimp for Android armv7
            condition: eq('${{ variables.android_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Android-arm64-v8a/libassimp.so $(build.SourcesDirectory)/$(package_folder)/Plugins/android/arm64/libassimp.so
            displayName: Install Assimp for Android arm64
            condition: eq('${{ variables.android_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-Android-x86/libassimp.so $(build.SourcesDirectory)/$(package_folder)/Plugins/android/x86/libassimp.so
            displayName: Install Assimp for Android x86
            condition: eq('${{ variables.android_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-iOS-armv7/libassimp.a $(build.SourcesDirectory)/$(package_folder)/Plugins/ios/armv7/libassimp.a
            displayName: Install Assimp for iOS armv7
            condition: eq('${{ variables.ios_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-iOS-arm64/libassimp.a $(build.SourcesDirectory)/$(package_folder)/Plugins/ios/arm64/libassimp.a
            displayName: Install Assimp for iOS arm64
            condition: eq('${{ variables.ios_enabled }}', 'true')

          - script: yes | cp -f $(Pipeline.Workspace)/Assimp-iOS-x86_64/libassimp.a $(build.SourcesDirectory)/$(package_folder)/Plugins/ios/x64/libassimp.a
            displayName: Install Assimp for iOS x86_64
            condition: eq('${{ variables.ios_enabled }}', 'true')

          - script: yes | cp -f $(build.SourcesDirectory)/README.md $(build.SourcesDirectory)/$(package_folder)/README.md
            displayName: Copy README

          - script: yes | cp -f $(build.SourcesDirectory)/LICENSE.md $(build.SourcesDirectory)/$(package_folder)/LICENSE.md
            displayName: Copy License

          - task: DeleteFiles@1
            inputs:
              sourceFolder: $(build.SourcesDirectory)/$(package_folder)
              contents: "**/.gitkeep"

          - publish: $(build.SourcesDirectory)/$(package_folder)
            artifact: UnityPackage

########################################################################################################################
## Publishing
########################################################################################################################

  # - stage: publishing
  #   displayName: Publishing
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   jobs:
  #     - job: publishing
  #       displayName: Publishing
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - download: current
  #           artifact: final_package

  #         - task: Npm@1
  #           displayName: Publishing package
  #           inputs:
  #             workingDir: $(build.SourcesDirectory)/$(package_folder)
  #             command: publish
  #             publishRegistry: useFeed
  #             publishFeed: $(System.TeamProjectId)/$(publish_feed)
