source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins

gem "just-the-docs", "~> 0.3"

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "wdm", "~> 0.1.0" if Gem.win_platform?

gem "webrick", "~> 1.7"

gem "activesupport", ">= 4.1.11"
