source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins

gem "just-the-docs", "~> 0.3"

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
