name: Build

on:
  push:
    branches:
      - main
      - master
      - develop
      - release/*

env:
  AssimpVersion: 4.1.0
  AssimpNetVersion: 4.1.0

jobs:
  build:
    name: Build
    uses: ./.github/workflows/package_generation.yml
    with:
      assimpVersion: 4.1.0
      assimpNetVersion: 4.1.0
