name: Build

on:
  push:
    branches:
      - main
      - master
      - develop
      - release/*

env:
  AssimpVersion: 4.1.0
  PackageFolder: "com.arsenstudio.assimp"

jobs:
  build_assimpnet:
    name: Build AssimpNet
    runs-on: windows-latest
    env:
      Solution: '**/*.sln'
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
    steps:
      - uses: actions/checkout@v3

      - name: Download AssimpNet sources
        uses: actions/checkout@v3
        with:
          repository: 'intelligide/assimpnet-unity'
          path: 'assimpnet'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Restore solution
        run: nuget restore ${{ env.Solution }}

      - name: Build app for release
        run: msbuild ${{ env.Solution }} -property:Configuration=${{ env.BuildConfiguration }} -property:Platform=${{ env.BuildPlatform }}

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_net
          path: assimpnet/AssimpNet/bin/Release

  build_assimp_win:
    name: Build Assimp for Windows
    runs-on: windows-2022
    env:
      GeneratorName: Visual Studio 17 2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - GeneratorArch: x64
            BuildArch: x64
          - GeneratorArch: Win32
            BuildArch: x86
    steps:
      - name: Download Assimp sources
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://github.com/assimp/assimp/archive/v${{ env.AssimpVersion }}.zip" -OutFile assimp.zip

      - name: Extract Assimp sources
        run: 7z x assimp.zip

      - name: Configure Assimp
        run: cmake -G "${{ matrix.GeneratorName }}" -A ${{ matrix.GeneratorArch }} -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel
            -DASSIMP_BUILD_TESTS=OFF -DASSIMP_NO_EXPORT=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON
        working-directory : assimp-${{ env.AssimpVersion }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: ${{ matrix.BuildArch }}

      - name: Build Assimp
        run: msbuild assimp-${{ env.AssimpVersion }}/Assimp.sln -property:Configuration=MinSizeRel

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_win_${{ matrix.BuildArch }}
          path: assimp-${{ env.AssimpVersion }}/bin/MinSizeRel

  build_assimp_linux:
    name: Assimp for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BuildArch: [x64]
    steps:
      - name: Install Ninja
        run: sudo apt-get update -yqq && sudo apt install -y ninja-build

      - name: Extract Assimp sources
        run: curl -L https://github.com/assimp/assimp/archive/v$(assimp_version).zip -o assimp.zip

      - name: Extract Assimp sources
        run: unzip assimp.zip

      - name: Configure Assimp
        run: cmake -G Ninja -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel
            -DASSIMP_BUILD_TESTS=OFF -DASSIMP_NO_EXPORT=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON
        working-directory : assimp-${{ env.AssimpVersion }}

      - name: Build Assimp
        run: ninja
        working-directory : assimp-${{ env.AssimpVersion }}

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_linux_${{ matrix.BuildArch }}
          path: assimp-${{ env.AssimpVersion }}/lib

  build_assimp_android:
    name: Build Assimp for Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        AndroidABI: [armeabi-v7a, arm64-v8a, x86]
    steps:
      - name: Install Ninja
        run: sudo apt-get update -yqq && sudo apt install -y ninja-build

      - name: Extract Assimp sources
        run: curl -L https://github.com/assimp/assimp/archive/v$(assimp_version).zip -o assimp.zip

      - name: Extract Assimp sources
        run: unzip assimp.zip

      - name: Configure Assimp
        run: cmake -G Ninja -S . -B . -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=${{ matrix.AndroidABI }}
            -DASSIMP_BUILD_TESTS=OFF -DASSIMP_ANDROID_JNIIOSYSTEM=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
            -DCMAKE_TOOLCHAIN_FILE=${{ env.ANDROID_SDK_ROOT }}/ndk-bundle/build/cmake/android.toolchain.cmake
            -DASSIMP_NO_EXPORT=ON -DBUILD_SHARED_LIBS=ON
        working-directory : assimp-${{ env.AssimpVersion }}

      - name: Build Assimp
        run: ninja
        working-directory : assimp-${{ env.AssimpVersion }}

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_android_${{ matrix.AndroidABI }}
          path: assimp-${{ env.AssimpVersion }}/lib

  build_assimp_macos:
    name: Build Assimp for Mac OS X x86_64
    runs-on: 'macos-latest'
    steps:
      - name: Extract Assimp sources
        run: curl -L https://github.com/assimp/assimp/archive/v$(assimp_version).zip -o assimp.zip

      - name: Extract Assimp sources
        run: unzip assimp.zip

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Configure Assimp
        run: cmake -G Xcode -S . -B . -DCMAKE_BUILD_TYPE=MinSizeRel
            -DASSIMP_BUILD_TESTS=OFF -DASSIMP_NO_EXPORT=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON
        working-directory : assimp-${{ env.AssimpVersion }}

      - run: xcodebuild -scheme ALL_BUILD -configuration MinSizeRel -sdk macosx13.1
        working-directory : assimp-${{ env.AssimpVersion }}

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_macos_x86_64
          path: assimp-${{ env.AssimpVersion }}/lib/MinSizeRel

  build_assimp_ios:
    name: Build Assimp for iOS
    runs-on: 'macos-latest'
    env:
      ios_archs: "armv7 arm64 x86_64"
    steps:
      - name: Extract Assimp sources
        run: curl -L https://github.com/assimp/assimp/archive/v$(assimp_version).zip -o assimp.zip

      - name: Extract Assimp sources
        run: unzip assimp.zip

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Assimp
        run: ./build.sh --archs="${{ env.ios_archs }}" --stdlib=libc++ --no-fat --std=c++14
        working-directory: assimp-${{ env.AssimpVersion }}/port/iOS

      - uses: actions/upload-artifact@v3
        with:
          name: assimp_ios
          path: assimp-${{ env.AssimpVersion }}/lib/iOS


  build_docs:
    name: Build Docs
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: docs

      - name: Build docs with Jekyll
        run: bundle exec jekyll build
        working-directory: docs

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_site

  packaging:
    name: Packaging
    runs-on: ubuntu-latest
    env:
      ArtifactTemporaryDir: artifacts
    needs:
      - build_assimpnet
      - build_assimp_win
      - build_assimp_linux
      - build_assimp_android
      - build_assimp_macos
      - build_assimp_ios
      - build_docs
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: ${{ env.ArtifactTemporaryDir }}

      - name: Copy Docs
        run: cp -f -R ${{ env.ArtifactTemporaryDir }}/docs ${{ env.PackageFolder }}/Documentation~

      - name: Install AssimpNet
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_net/netstandard2.0/AssimpNet.dll ${{ env.PackageFolder }}/AssimpNet.dll

      - name: Install Assimp for Windows x64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_win_x64/assimp-vc140-mt.dll ${{ env.PackageFolder }}/Plugins/win/x86_64/assimp.dll

      - name: Install Assimp for Windows x86
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_win_x86/assimp-vc140-mt.dll ${{ env.PackageFolder }}/Plugins/win/x86/assimp.dll

      - name: Install Assimp for Linux x86_64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_linux_x64/libassimp.so ${{ env.PackageFolder }}/Plugins/linux/x86_64/libassimp.so

      - name: Install Assimp for Mac OS X x86_64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_macos_x86_64/libassimp.dylib ${{ env.PackageFolder }}/Plugins/osx/x86_64/libassimp.dylib

      - name: Install Assimp for Android armv7
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_android_armeabi-v7a/libassimp.so ${{ env.PackageFolder }}/Plugins/android/armv7/libassimp.so

      - name: Install Assimp for Android arm64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_android_arm64-v8a/libassimp.so ${{ env.PackageFolder }}/Plugins/android/arm64/libassimp.so

      - name: Install Assimp for Android x86
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_android_x86/libassimp.so ${{ env.PackageFolder }}/Plugins/android/x86/libassimp.so

      - name: Install Assimp for iOS armv7
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_ios/armv7/libassimp.a ${{ env.PackageFolder }}/Plugins/ios/armv7/libassimp.a

      - name: Install Assimp for iOS arm64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_ios/arm64/libassimp.a ${{ env.PackageFolder }}/Plugins/ios/arm64/libassimp.a

      - name: Install Assimp for iOS x86_64
        run: cp -f ${{ env.ArtifactTemporaryDir }}/assimp_ios/x86_64/libassimp.a ${{ env.PackageFolder }}/Plugins/ios/x64/libassimp.a

      - name: Copy README
        run: cp -f README.md ${{ env.PackageFolder }}/README.md

      - name: Copy License
        run: cp -f LICENSE.md ${{ env.PackageFolder }}/LICENSE.md

      - name: Delete gitkeep files
        run: find ${{ env.PackageFolder }} -name '.gitkeep' -delete

      - uses: actions/upload-artifact@v3
        with:
          name: final_package
          path: ${{ env.PackageFolder }}

  # publishing:
  #   name: Publishing
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   needs: packaging
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: final_package

  #     - uses: actions/setup-node@v3
  #       with:
  #         registry-url: 'https://npm.pkg.github.com'

  #     - name: Publishing package
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
