name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/package_generation.yml
    with:
      assimpVersion: 4.1.0
      AssimpNetVersion: 4.1.0

  publishing:
    name: Publishing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.packageName }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      - run: |
          cat <<EOF > .npmrc
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          registry=https://npm.pkg.github.com/@${{ github.repository_owner }}
          EOF

      - name: Publishing package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
