name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/package_generation.yml
    with:
      assimpVersion: 4.1.0
      assimpNetVersion: 4.1.0

  publishing:
    name: Publishing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          paths: packages

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://upm.frozenstorminteractive.com'

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp.android
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp.ios
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp.linux
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp.macos
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}

      - name: Publishing package
        run: npm publish
        working-directory: packages/com.frozenstorminteractive.assimp.windows
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSI_REGISTRY_TOKEN }}
